### ISSUE TITLE
IE 9 Error

### ISSUE THREAD

**Issue by samcus** [madferro/Sniff.js#2]
A project I'm working on requires IE9 support.

IE9 returns the following error: SCRIPT5007: Unable to get value of the property 'add': object is null or undefined

**Comment by madferro** [comment]
Hi samcus, thank you for the report.
I updated to versione 1.2, that issue now is fixed (i tried it and worked for me). 
Can you please download the new version and let me know if everything works fine?
Thank you!

**Comment by samcus** [comment]
Looks to be working! Thanks for the quick fix. Much appreciated!
